DOCSP-40133: custom auth provider
mongodb/docs-kafka-connector pull request #163
Opened 2024-06-10 19:36 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-kafka-connector/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-40133>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/kafka-connector/DOCSP-40133-custom-authprovider/security-and-authentication/mongodb-aws-auth/#custom-authentication-provider

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Are all the links working?
- [x] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-06-11 14:05 UTC, mcmorisi requested changes

2024-06-13 11:13 UTC, RWaltersMA commented
Its a custom authentication provider, not specific to AWS IAM. We are providing a sample to do AWS IAM Auth though, the way the docs are written sounds like it is just AWS IAM support.

2024-06-13 20:04 UTC, mcmorisi approved these changes
LGTM. Really great job on this!

2024-06-24 17:50 UTC, RWaltersMA commented on source/security-and-authentication/custom-auth.txt
> +Group IAM Role.
Atlas User Group

2024-06-24 17:50 UTC, RWaltersMA commented on source/security-and-authentication/custom-auth.txt
> +        "mongodbaws.auth.mechanism.roleArn": "arn:aws:iam::99999999:role/KafkaAtlasRole"
replace arn:aws:iam with <ARN of AWS IAM Role>

2024-06-24 17:50 UTC, RWaltersMA commented on source/security-and-authentication/custom-auth.txt
> +        "mongodbaws.auth.mechanism.roleArn": "arn:aws:iam::99999999:role/KafkaAtlasRole"
aws iam ARN something like that

2024-06-24 18:33 UTC, RWaltersMA commented
LGTM

2024-06-24 19:44 UTC, merged