DOCSP-26355: startup mode
mongodb/docs-kafka-connector pull request #59
Opened 2022-12-02 16:20 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-kafka-connector/blob/master/REVIEWING.md)

JIRA - https://jira.mongodb.org/browse/DOCSP-26355
Staging
Main page: https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-26355-start-specified-time/source-connector/configuration-properties/startup-properties/#std-label-source-configuration-startup
Usage example: https://docs-mongodbcom-staging.corp.mongodb.com/kafka-connector/docsworker-xlarge/DOCSP-26355-start-specified-time/source-connector/usage-examples/copy-existing-data/#std-label-source-usage-example-copy-existing-data

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?

2022-12-05 02:18 UTC, stIncMale requested changes

2022-12-05 14:16 UTC, rustagir commented on source/source-connector/configuration-properties.txt
> +   Startup Mode </source-connector/configuration-properties/copy-existing>
Thanks for clarifying!

2022-12-05 14:38 UTC, rustagir commented on source/source-connector/configuration-properties/copy-existing.txt
> +             startup.mode.copy.existing.namespace.regex=stats\\.page.*
I added the second `\` to match what I saw on [this line](https://github.com/mongodb/mongo-kafka/blob/40ae109680c3ec1af5c03850b76154da91d87d02/src/main/java/com/mongodb/kafka/connect/source/MongoSourceConfig.java#L358) in the source.

2022-12-06 12:10 UTC, rozza requested changes
Looking good - added a couple of suggestions for improvements

2022-12-06 15:57 UTC, rustagir commented on source/whats-new.txt
> +  ``copy.existing.allow.disk.use`` :ref:`configuration property <source-configuration-startup>`
adding a 1.9 what's new section

2022-12-09 09:58 UTC, rozza approved these changes
LGTM

2022-12-09 15:51 UTC, mongoKart requested changes
Awesome. A few really small changes.

2022-12-09 15:51 UTC, mongoKart commented on source/source-connector/configuration-properties/startup.txt
> +         ``databaseName.collectionName``.
Issue: Style guide recommends avoiding Latin abbreviations

```suggestion
         and collection separated by a period (for example,
         ``databaseName.collectionName``).
```

2022-12-09 15:51 UTC, mongoKart commented on source/source-connector/configuration-properties/startup.txt
> +          In the following example, the regular expression setting matches
Issue: Compound modifier

Suggestion:

```suggestion
          In the following example, the regular-expression setting matches
```

2022-12-09 15:51 UTC, mongoKart commented on source/source-connector/configuration-properties/startup.txt
> +         to use temporary disk storage.
Issue: Something about this phrasing sounds a little off.

Suggestion:

```suggestion
         the connector uses temporary disk storage for the copy existing aggregation 
```

Or:

```suggestion
         the connector instructs the copy existing aggregation 
         to use temporary disk storage. 
```

...or something similar.

2022-12-09 16:20 UTC, mongoKart approved these changes
LGTM!

2022-12-09 16:51 UTC, merged